### ISSUE TITLE
Problem Injecting the dll

### ISSUE THREAD

**Issue by Gambit5432** [hellokittyfan48/ww-enhancer#5]
I used undetected CE,Xenos,Process hacker 2 it shows the same error.I am using Pipsi for the bypass

![image](https://github.com/hellokittyfan48/WW-enhancer/assets/122726052/ab3266f1-c7c7-4873-b2e7-1aabca36f1e1)

**Comment by hellokittyfan48** [comment]
Have you tried following the instructions given in the README?

**Comment by Gambit5432** [comment]
> Have you tried following the instructions given in the README?

yes followed all the steps still the same error

**Comment by ravzkie12** [comment]
Same with changing characters.

**Comment by hellokittyfan48** [comment]
> Same with changing characters.

Yes, I'm aware.

> Same with changing characters.

Load into the game fully, if that doesn't work, join the Discord.
