### ISSUE TITLE
Recommendations and fixes

### ISSUE THREAD

**Issue by fzl122122** [hellokittyfan48/ww-enhancer#6]
Dear author, I found that when I was using this project, I always crashed when entering a copy, I hope you can fix it.
I'd like you to introduce a whole game boost and not just a character boost, and I'd appreciate it if you could.

**Comment by hellokittyfan48** [comment]
Please report any crashes in the Discord, world speed is coming in the next update.

**Comment by fzl122122** [comment]
> 请报告 Discord 中的任何崩溃，世界速度将在下一次更新中到来。

Thank you for your contribution, great work.
