### ISSUE TITLE
Injection failed

### ISSUE THREAD

**Issue by fzl122122** [hellokittyfan48/ww-enhancer#7]
Unable to inject, even if it enters the game, it is not a crash but a failure to inject

**Comment by AzdoBoi** [comment]
> Unable to inject, even if it enters the game, it is not a crash but a failure to inject

Try another injector, or make your own injector, my mine is work fine.

**Comment by SphinX2k6** [comment]
@AzdoBoi it would be really kind of you , if you share that injector with us too.

**Comment by AzdoBoi** [comment]
> @AzdoBoi it would be really kind of you , if you share that injector with us too.

unfortunately I can't share it, as it's private and uses my own bypass

**Comment by AzdoBoi** [comment]
But if you want to use another injector, why not try joining @hellokittyfan48 discord and use the injector that is on her server discord

**Comment by hellokittyfan48** [comment]
> @AzdoBoi it would be really kind of you , if you share that injector with us too.

Join the discord
