### ISSUE TITLE
god mode/infinite hp

### ISSUE THREAD

**Issue by havok585** [hellokittyfan48/ww-enhancer#8]
just a suggestion here,

god mode active is known to cause issues with echo skill, basically they wont do damage, (exception is the bell-borne turtle echo) and
also perfect dodge skill becomes UNusable.

What if instead of god mode (ignoring damage), have a large hp pool (infinite basically)that is a fixed value
example u have 16000 hp, u put a value of 100.000, so whatever attack the enemy does it will hurt you but the value will regenerate back to 100.000 in a fraaction of a second (this is how trainers from other games work that have the  "inf. hp" function active);

wouldnt that make the echo skill and perfect doge then USABLE ? 

just a suggestion :)

**Comment by hellokittyfan48** [comment]
HP is handled by the server, not possible.
